name: 'GitHub Actions Demo'

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  schedule:
    - cron: '0 21 * * *'

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs
  checkin-job:
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Install Python'
        run: |
          sudo apt update
          sudo apt install python3
      - name: 'Install dependent package'
        run: |
          pip3 install requests
          pip3 install python-telegram-bot
      - name: 'Run python'
        env:
          TG_TO: ${{ secrets.TELEGRAM_TO }}
          TG_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          python3 check.py <<EOF
          ${{secrets.config}}
          EOF

  weather-prediction-job:
    needs: checkin-job
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get weather report'
        run: bash ./weather.sh
      - name: 'Read result.txt'
        id: read_file
        uses: juliangruber/read-file-action@v1
        with:
          path: ./result.txt
      - name: send weather message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ steps.read_file.outputs.content }}
          # document: ./result.txt
    