name: 'GitHub Actions Weather Bot'

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  schedule:
    - cron: '0 21 * * *'

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get weather report'
        run: bash ./weather.sh
      - name: 'Read result.txt'
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./result.txt
      - name: send weather message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ steps.package.outputs.content }}
          # document: ./result.txt
